### ISSUE TITLE
新增jest和jest-ts模板

### ISSUE THREAD

**Issue by helinjiang** [matmanjs/create-matman-app#3]
已经增加了 `demo/jest` 示例，增加 `--template=jest` 和 `--template=jest-ts` 两个模板

同时，将 `demo/matman-ts` 修改为 `demo/mocha-ts`，匹配的命令为 `--template=mocha-ts` ，保持统一，当然，保留但不推荐  `--template=ts` 和 `--ts`

**Comment by damonare** [comment]
done
